apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ .Values.persistentVolumeClaim.name }}
spec:
  accessModes: 
   - {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}